SUREEHA20068/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SUREEHA20068.Data;
using SUREEHA20068.Models;

namespace SUREEHA20068.Controllers
{
    public class OrdersController : Controller
    {
        private AppDb db = new AppDb();

        // GET: Orders
        public async Task<ActionResult> Index()
        {
            var orders = db.orders.Include(o => o.customer).Include(o => o.employee).Include(o => o.shipper);
            return View(await orders.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await db.orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Contacename");
            ViewBag.EmployeeId = new SelectList(db.employees, "EmployeeId", "FirstName");
            ViewBag.ShipperId = new SelectList(db.shippers, "ShipperId", "CompanyName");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "orderId,OrderDate,Freight,CustomerId,EmployeeId,ShipperId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.orders.Add(order);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Contacename", order.CustomerId);
            ViewBag.EmployeeId = new SelectList(db.employees, "EmployeeId", "FirstName", order.EmployeeId);
            ViewBag.ShipperId = new SelectList(db.shippers, "ShipperId", "CompanyName", order.ShipperId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await db.orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Contacename", order.CustomerId);
            ViewBag.EmployeeId = new SelectList(db.employees, "EmployeeId", "FirstName", order.EmployeeId);
            ViewBag.ShipperId = new SelectList(db.shippers, "ShipperId", "CompanyName", order.ShipperId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "orderId,OrderDate,Freight,CustomerId,EmployeeId,ShipperId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Contacename", order.CustomerId);
            ViewBag.EmployeeId = new SelectList(db.employees, "EmployeeId", "FirstName", order.EmployeeId);
            ViewBag.ShipperId = new SelectList(db.shippers, "ShipperId", "CompanyName", order.ShipperId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await db.orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Order order = await db.orders.FindAsync(id);
            db.orders.Remove(order);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SUREEHA20068/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@

</head>
<body>
    @Html.Partial("_Navbar")
    @*<li>@Html.ActionLink("สินค้า", "Index", "Products")</li>
    <li>@Html.ActionLink("ประเภทสินค้า", "Index", "Categories")</li>
    <li>@Html.ActionLink("ผู้จัดจำหนาย", "Index", "Suppliers")</li>
    <li>@Html.ActionLink("ลูกค้า", "Index", "Customers")</li>
    <li>@Html.ActionLink("พนักงาน", "Index", "Employees")</li>
    <li>@Html.ActionLink("รายการสั่งสินค้า", "Index", "Orders")</li>
    <li>@Html.ActionLink("รายละเอียดการสั่งสินค้า", "Index", "OrderDetails")</li>
    <li>@Html.ActionLink("ผู้จัดส่ง", "Index", "Shippers")</li>*@



    <div class="container body-content">
        @RenderBody()
        @*<hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>




    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)






</body>
</html>

SUREEHA20068/Views/Shared/_Navbar.cshtml
@*<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3  border-bottom shadow-sm" style="background-color: #D8BFD8;">
     <h5 class="my-0 mr-md-auto font-weight-normal">Book Store </h5>

         <a class="nav-link dropdown-toggle" href="#" id="ddlMenu1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    จัดการสินค้า
         </a>
         <div class="dropdown-menu" aria-labelledby="ddlMenu1">
             <a class="dropdown-item" href="~/Categories">ประเภทสินค้า</a>
             <a class="dropdown-item" href="~/Customers">สินค้า</a>
         </div>*@



@*<button type="button" class="btn btn-light">Register </button>
    <button type="button" class="btn btn-light">Login</button>*@

@*@Html.Partial("_LoginPartial")*@

@*</div>*@


@*<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #D8BFD8;">
    <a class="navbar-brand" href="/">BOOK STORE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="ddlMenu1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             จัดการสินค้า
                </a>
                <div class="dropdown-menu" aria-labelledby="ddlMenu1">
                    <a class="dropdown-item" href="~/Categories">ประเภทสินค้า</a>
                    <a class="dropdown-item" href="~/Products">สินค้า</a>

                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="~/Orders/">รายการสั่งซื้อ</a>
            </li>
        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</nav>*@

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal"> BOOK STORE </h5>
        <a class="p-2 text-dark" href="~/Products/Main">สินค้าทั้งหมด</a>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark dropdown-toggle" href="#" id="ddlMenu1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                จัดการสินค้า
            </a>
            <div class="dropdown-menu" aria-labelledby="ddlMenu1">
                <a class="dropdown-item" href="~/Categories">ประเภทสินค้า</a>
                <a class="dropdown-item" href="~/Products">สินค้า</a>
                <a class="dropdown-item" href="~/Suppliers">ผู้ผลิต</a>

            </div>
            <a class="p-2 text-dark" href="~/Shippers">การจัดส่ง</a>

        </nav>
        @Html.Partial("_LoginPartial")
    </div>

SUREEHA20068/Views/Shared/_PartialHomepage.cshtml
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img src="" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">ใส่ตะกร้า</a>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img src="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">ใส่ตะกร้า</a>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img src="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">ใส่ตะกร้า</a>
                    </div>
                </div>
            </div>
        </div>
























    </div>